name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    # see https://github.com/pre-commit/action/#using-this-action
    - name: pre-commit checks
      uses: pre-commit/action@v3.0.1
      env:
        # it's okay for github to commit to main/master
        SKIP: no-commit-to-branch
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions poetry==1.4.1
    - name: Test with tox
      run: tox